# Site settings
# These are used to personalize your new site.
title: Joshua Philip Ingalls # your name here
logo: "/images/Headshot.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Science in Cybersecurity (Class of 2025)
  <br /><br />
  <a href="https://csuniv.joinhandshake.com/profiles/32857937">View My Resume</a>
  <br /><br />
  <a href="https://www.linkedin.com/in/joshua-ingalls-99b755223/">View My LinkedIn Profile</a>
repository: "csci-csu/csci-portfolio"
github_username:  ThunderboltG # update with your username
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

